const arr = [100,20,30,40,50]
arr.push(60)
console.log(arr)
arr.pop()
console.log(arr)
arr.splice(0,2,100,110)
console.log(arr)
const finarr = arr.slice(0,4)
console.log(finarr)
arr.unshift(200)
console.log(arr)
arr.shift()
console.log(arr)
const finarr1 = arr.indexOf(30)
console.log(finarr1)
const finarr2 = arr.includes(100)
console.log(finarr2)
const finarr3 = arr.at(3)
console.log(finarr3)
const finarr4 = arr.lastIndexOf(50)
console.log(finarr4)
const finarr5 = arr.sort()
console.log(finarr5)
const finarr6 = arr.reverse()
console.log(finarr6)